import Head from "next/head";
import * as React from "react";
import { useState, Fragment, useMemo } from "react";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import RiveComponent from "@rive-app/react-canvas";
import Image from "next/image";
import Link from "next/link";
import * as Icon from "react-feather";

export default function Home() {
  const title = "Designer and Developer";
  const imgLoader = ({ src, width, quality }) => {
    return `/${src}?w=${width}&q=${quality || 75}`;
  };
  const highlight = "About";

  return (
    <>
      <Head>
        <title>About Florian | Design With Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation title={title} highlight={highlight} />
      <main class="max-md:w-[90%] min-h-[100vh] w-full max-w-7xl pl-[10%] pr-[10%] m-auto bg-white">
        <div class="w-full h-[35vh] pt-5">
          <RiveComponent
            src="./animations/florian_animation.riv"
            class="max-w-[500px] h-auto object-contain m-auto"
          />
        </div>
        <div class="gap-16 grid grid-cols-2 max-md:grid-cols-1">
          <div>
            <div class="flex gap-8 mb-6 max-lg:flex-col">
              <Image
                loader={imgLoader}
                src="./images/florian_student.jpg"
                class="inline-flex object-cover object-top max-h-64"
                width={200}
                height={100}
              />
              <div>
                <h1 class="text-2xl font-medium mb-3">About me</h1>
                <p>
                  <span class="font-bold italic">Nice to meet you!</span> - My
                  name is Florian and I am currently 22 years old. I am a
                  designer and developer and I love to create beautiful
                  products. Currently I am studying at the Hochschule fuer
                  Gestaltung, also known as just HfG, in Schwaebisch Gmuend,
                  Germany.
                </p>
              </div>
            </div>
            <p>
              Beside my desire to work between design and code I love working
              with CSS and creating animations for web and mobile applications.
            </p>
          </div>
          <div class="flex flex-col gap-6">
            <h2 class="font-medium text-lg">Work</h2>
            <div class="flex w-full justify-between">
              <div class="flex gap-2 place-items-center ">
                <Image 
                  loader={imgLoader}  
                  src="./images/company_hfg.jpg"
                  class="block flex-shrink-0 relative object-contain object-center rounded-full border border-gray-200 p-1"
                  width={40}
                  height={40}
                />
                <div>
                  <h3 class="font-medium text-md">Digital Strategist and Designer</h3>
                  <p class="text-sm text-gray-500">Metahype</p>
                </div>
              </div>
              <p class="text-gray-500">2020 - present</p>
            </div>
            <div class="flex w-full justify-between">
              <div class="flex gap-2 place-items-center ">
                <Image 
                  loader={imgLoader}  
                  src="./images/company_hfg.jpg"
                  class="block flex-shrink-0 relative object-contain object-center rounded-full border border-gray-200 p-1"
                  width={40}
                  height={40}
                />
                <div>
                  <h3 class="font-medium text-md">Digital Strategist and Designer</h3>
                  <p class="text-sm text-gray-500">Metahype</p>
                </div>
              </div>
              <p class="text-gray-500">2020 - present</p>
            </div>
            <div class="flex w-full justify-between">
              <div class="flex gap-2 place-items-center ">
                <Image 
                  loader={imgLoader}  
                  src="./images/company_hfg.jpg"
                  class="block flex-shrink-0 relative object-contain object-center rounded-full border border-gray-200 p-1"
                  width={40}
                  height={40}
                />
                <div>
                  <h3 class="font-medium text-md">Digital Strategist and Designer</h3>
                  <p class="text-sm text-gray-500">Metahype</p>
                </div>
              </div>
              <p class="text-gray-500">2020 - present</p>
            </div>
            <div class="flex w-full justify-between">
              <div class="flex gap-2 place-items-center ">
                <Image 
                  loader={imgLoader}  
                  src="./images/company_hfg.jpg"
                  class="block flex-shrink-0 relative object-contain object-center rounded-full border border-gray-200 p-1"
                  width={40}
                  height={40}
                />
                <div>
                  <h3 class="font-medium text-md">Digital Strategist and Designer</h3>
                  <p class="text-sm text-gray-500">Metahype</p>
                </div>
              </div>
              <p class="text-gray-500">2020 - present</p>
            </div>
          </div>
          <div class="flex flex-col gap-6">
            <h2 class="font-medium text-lg">Side projects</h2>
            <div class="flex w-full justify-between">
              <div class="flex gap-2 place-items-center ">
                <Image 
                  loader={imgLoader}  
                  src="./images/project_curations.jpg"
                  class="block flex-shrink-0 relative object-contain object-center rounded-full border border-gray-200 p-1"
                  width={40}
                  height={40}
                />
                <div>
                  <h3 class="font-medium text-md">Curations</h3>
                  <p class="text-sm text-gray-500">Website featuring useful curations for designers and developers</p>
                </div>
              </div>
            </div>
          </div>
          <div class="flex flex-col gap-4">
            <h2 class="font-medium text-lg">Connect</h2>
            <div class="flex gap-4">
              <Link class="font-medium transition-all text-black hover:opacity-75 border-b-2 border-b-black" href={"#"}>Read.cv</Link>
              <Link class="font-medium transition-all text-black hover:opacity-75 border-b-2 border-b-black" href={"#"}>GitHub</Link>
              <Link class="font-medium transition-all text-black hover:opacity-75 border-b-2 border-b-black" href={"#"}>LinkedIn</Link>
            </div>
          </div>
        </div>
        <div class="h-64"></div>
      </main>
      <Footer />
    </>
  );
}
