import Head from "next/head";
import * as React from "react";
import { useState, useCallback } from "react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import RiveComponent from "@rive-app/react-canvas";
import Image from "next/image";
import Link from "next/link";
import * as Icon from "react-feather";

export default function Home() {
  const title = "Designer and Developer";
  const imgLoader = ({ src, width, quality }) => {
    return `/${src}?w=${width}&q=${quality || 75}`;
  };

  const [domLoaded, setDomLoaded] = useState(false);

  React.useEffect(() => {
    setDomLoaded(true);
  }, []);

  const concepts = [
    {
      title: "Nutri",
      description: "Social Food App",
      icon: "./images/concept_icons/concept-icon_nutri.svg",
    },
    {
      title: "Stackoverflow",
      description: "Redesign & Extension",
      icon: "./images/concept_icons/concept-icon_stackoverflow.svg",
    },
    {
      title: "Solarized",
      description: "Autobahn & Energy",
      icon: "./images/concept_icons/concept-icon_solarized.svg",
    },
    {
      title: "Homicides",
      description: "ThreeJS Visualization",
      icon: "./images/concept_icons/concept-icon_solarized.svg",
    },
  ];

  const shuffledConcepts = !domLoaded
    ? concepts
    : concepts.sort(() => 0.5 - Math.random());

  const highlight = "Concepts";

  return (
    <>
      <Head>
        <title>About Florian | Design With Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation title={title} highlight={highlight} />
      <main className="max-md:w-[90%] min-h-[100vh] w-full max-w-6xl pl-[5%] pr-[5%] m-auto bg-white">
        <div className="flex flex-col items-left justify-left h-full pt-32 max-md:pt-16 mb-8">
          <h1 className="text-4xl font-bold text-left mb-3">Concepts</h1>
          <h2 className="text-2xl font-medium text-left text-gray-500">
            Smaller creations and ideas.
          </h2>
        </div>
        <div className="min-h-96 flex flex-col place-items-start w-full gap-4">
          {domLoaded &&
            shuffledConcepts.map((concept, index) => (
              <div
                key={index}
                className="bg-transparent rounded-2xl flex justify-center place-items-center"
              >
                <div className="cursor-pointer transition-all hover:bg-gray-100 flex flex-wrap flex-row gap-4 justify-center px-4 py-3 rounded-lg place-items-center text-gray-600 hover:text-black relative -left-4">
                  <Image
                    loader={imgLoader}
                    src={concept.icon}
                    alt="Nutri Blueprint Icon"
                    className="rounded-xl"
                    width={48}
                    height={48}
                  />
                  <div>
                    <p className="text-lg font-medium">{concept.title}</p>
                    <p className="text-base">{concept.description}</p>
                  </div>
                </div>
              </div>
            ))}
        </div>
      </main>
      <Footer />
    </>
  );
}
