import Head from "next/head";
import * as React from "react";
import { useState, Fragment } from "react";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";
import Image from "next/image";
import Link from "next/link";
import * as Icon from "react-feather";
import { Menu, Transition } from "@headlessui/react";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Home() {
  const title = "Designer and Developer";
  const imgLoader = ({ src, width, quality }) => {
    return `/${src}?w=${width}&q=${quality || 75}`;
  };
  const [item, setItem] = useState(0);
  const rect = React.useRef(null);

  const changeItem = () => {
    if (item === 0) {
      setItem(1);
      rect.current.style.transform = "translateX(48px) translateY(-50%)";
    } else {
      setItem(0);
      rect.current.style.transform = "translateX(0%) translateY(-50%)";
    }
  };

  return (
    <>
      <Head>
        <title>Combining Design and Technology | Design With Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation title={title} />
      <main class="max-md:w-[90%] w-full max-w-7xl pl-[10%] pr-[10%] m-auto bg-white">
        <div class="h-[70vh] flex place-items-center justify-between">
          <div class="md:w-[50%]">
            <h1 class="text-5xl font-bold mb-6">Hey, I'm Florian</h1>
            <h2 class="text-3xl font-medium text-gray-700">
              A designer and developer building digital products.
            </h2>
            <div class="h-8"></div>
            <Link
              class="p-4 w-full max-w-[400px] flex place-items-center gap-6 bg-gray-100 border border-gray-300 transition-all hover:bg-gray-50 hover:border-gray-200 border-solid rounded-2xl"
              href={"#"}
            >
              <div class="h-[8px] w-[8px] flex-none flex justify-center place-items-center rounded-full bg-red-600 opacity-75">
                <div class="animate-ping h-[16px] w-[16px] absolute flex-none rounded-full bg-red-500 opacity-75"></div>
              </div>
              <p class="font-medium text-sm">
                Currently I am looking for internship opportunities in Europe or
                North America.
              </p>
            </Link>
          </div>
          <Image
            loader={imgLoader}
            src="main_header.png"
            alt="Header Image of Florian as Cartoon Character"
            class="mix-blend-exclusion max-md:hidden"
            width={250}
            height={250}
          />
        </div>
        <div>
          <h2 class="text-2xl font-medium text-black">
            As a designer and developer I see my role in leading projects that
            help companies to achieve their ambitious goals in creating
            something functionally and technologically useful for humanity
          </h2>
        </div>
        <div class="h-64"></div>
        <div>
          <div class="flex justify-between pb-[40px]">
            <h2 class="text-3xl font-medium text-black">Some of my projects</h2>
            <div class="flex gap-6 relative place-items-center pl-2 pr-2">
              <Icon.Grid
                onClick={changeItem}
                class="cursor-pointer text-gray-600 hover:text-black transition-all relative z-10"
              />
              <Icon.List
                onClick={changeItem}
                class="cursor-pointer text-gray-600 hover:text-black transition-all relative z-10"
              />
              <div
                ref={rect}
                class="w-[40px] h-[40px] left-0 top-[50%] translate-y-[-50%] rounded-md absolute bg-gray-100 border border-gray-200 transition-all"
              ></div>
            </div>
          </div>
          <div>
            <div class="grid grid-cols-2 gap-8">
              <Link href={"#"} class="group">
                <div class="bg-white shadow-md ring-1 ring-gray-100 rounded-md p-2 mb-6">
                  <Image
                    loader={imgLoader}
                    src="ambient_chat_preview.jpg"
                    alt="Heaer Image of Florian as Cartoon Character"
                    class="w-[100%] max-h-[256px] object-cover group-hover:opacity-80 transition-all"
                    width={250}
                    height={250}
                  />
                </div>
                <div class="flex place-items-center gap-2">
                  <h3 class="text-xl font-medium pb-1">Curations</h3>
                  <Icon.ArrowRight class="opacity-0 group-hover:opacity-100 transition-all relative" />
                </div>
                <p class="pb-2 text-gray-500">
                  Website featuring useful curations for designers and
                  developers
                </p>
                <div class="flex gap-4 text-xs text-gray-500">
                  <div class="flex gap-2 place-items-center">
                    <Icon.Calendar width={16} />
                    <p>Q4 2021</p>
                  </div>
                  <div class="flex gap-2 place-items-center">
                    <Icon.MapPin width={16} />
                    <p>Q4 2021</p>
                  </div>
                </div>
              </Link>
              <Link href={"#"} class="group">
                <div class="bg-white shadow-md ring-1 ring-gray-100 rounded-md p-2 mb-6">
                  <Image
                    loader={imgLoader}
                    src="ambient_chat_preview.jpg"
                    alt="Heaer Image of Florian as Cartoon Character"
                    class="w-[100%] max-h-[256px] object-cover group-hover:opacity-80 transition-all"
                    width={250}
                    height={250}
                  />
                </div>
                <div class="flex place-items-center gap-2">
                  <h3 class="text-xl font-medium pb-1">Curations</h3>
                  <Icon.ArrowRight class="opacity-0 group-hover:opacity-100 transition-all relative" />
                </div>
                <p class="pb-2 text-gray-500">
                  Website featuring useful curations for designers and
                  developers
                </p>
                <div class="flex gap-4 text-xs text-gray-500">
                  <div class="flex gap-2 place-items-center">
                    <Icon.Calendar width={16} />
                    <p>Q4 2021</p>
                  </div>
                  <div class="flex gap-2 place-items-center">
                    <Icon.MapPin width={16} />
                    <p>Q4 2021</p>
                  </div>
                </div>
              </Link>
              <Link href={"#"} class="group">
                <div class="bg-white shadow-md ring-1 ring-gray-100 rounded-md p-2 mb-6">
                  <Image
                    loader={imgLoader}
                    src="ambient_chat_preview.jpg"
                    alt="Heaer Image of Florian as Cartoon Character"
                    class="w-[100%] max-h-[256px] object-cover group-hover:opacity-80 transition-all"
                    width={250}
                    height={250}
                  />
                </div>
                <div class="flex place-items-center gap-2">
                  <h3 class="text-xl font-medium pb-1">Curations</h3>
                  <Icon.ArrowRight class="opacity-0 group-hover:opacity-100 transition-all relative" />
                </div>
                <p class="pb-2 text-gray-500">
                  Website featuring useful curations for designers and
                  developers
                </p>
                <div class="flex gap-4 text-xs text-gray-500">
                  <div class="flex gap-2 place-items-center">
                    <Icon.Calendar width={16} />
                    <p>Q4 2021</p>
                  </div>
                  <div class="flex gap-2 place-items-center">
                    <Icon.MapPin width={16} />
                    <p>Q4 2021</p>
                  </div>
                </div>
              </Link>
              <Link href={"#"} class="group">
                <div class="bg-white shadow-md ring-1 ring-gray-100 rounded-md p-2 mb-6">
                  <Image
                    loader={imgLoader}
                    src="ambient_chat_preview.jpg"
                    alt="Heaer Image of Florian as Cartoon Character"
                    class="w-[100%] max-h-[256px] object-cover group-hover:opacity-80 transition-all"
                    width={250}
                    height={250}
                  />
                </div>
                <div class="flex place-items-center gap-2">
                  <h3 class="text-xl font-medium pb-1">Curations</h3>
                  <Icon.ArrowRight class="opacity-0 group-hover:opacity-100 transition-all relative" />
                </div>
                <p class="pb-2 text-gray-500">
                  Website featuring useful curations for designers and
                  developers
                </p>
                <div class="flex gap-4 text-xs text-gray-500">
                  <div class="flex gap-2 place-items-center">
                    <Icon.Calendar width={16} />
                    <p>Q4 2021</p>
                  </div>
                  <div class="flex gap-2 place-items-center">
                    <Icon.MapPin width={16} />
                    <p>Q4 2021</p>
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>
        <div class="h-64"></div>
        <div class="flex gap-8 justify-between max-md:flex-col ">
          <div class="md:max-w-[50%]">
            <h2 class="text-2xl font-medium mb-4">More to my person</h2>
            <p class="text-gray-500">
              Being interested in technology and design would be a big
              understatement. I love creating useful products, trying out new
              things and adjusting key levers as long as necessary to give
              people the best experience possible. <br />
              <br /> The reason for doing this, is because I see myself not only
              as a designer or engineer of a product, much more can I imagine
              myself as the end-user that wants to have an accessible product
              that's usable. <br />
              <br /> If you want to read more to myself, you can click the
              button below or find me on{" "}
              <Link
                href="#"
                class="text-[#1281ed] inline-block border border-solid border-blue-100 rounded-md pl-1 pr-1"
              >
                Read.cv
              </Link>
              .
            </p>
            <div class="h-8"></div>
            <button
              class="bg-white text-black pr-4 pl-4 pt-2 pb-2 rounded-md hover:bg-gray-100 transition-all font-medium border border-solid border-gray-300"
              href="#"
            >
              About me
            </button>
          </div>
          <Image
            loader={imgLoader}
            src="photo_church.jpg"
            alt="Heaer Image of Florian as Cartoon Character"
            class="w-full h-full max-md:order-first max-md:mb-8 max-w-[350px] max-h-[500px] object-cover group-hover:opacity-80 transition-all rotate-3"
            width={250}
            height={600}
          />
        </div>
        <div class="h-64"></div>
        <div class="relative w-full h-[510px] bg-gray-50 rounded-xl overflow-hidden">
          <div class="w-full h-16 flex justify-between place-items-center pl-4 pr-4 border-b border-b-solid">
            <div class="flex place-items-center gap-3">
              <Image
                loader={imgLoader}
                src="memoji.png"
                alt="Florian Profile Avatar"
                class="rounded-full bg-white border border-solid p-1"
                width={48}
                height={48}
              />
              <p class="text-xl font-medium">Florian</p>
            </div>
            <div class="flex gap-4">
              <Icon.Video class="text-gray-300" />
              <Icon.Info class="text-gray-300" />
            </div>
          </div>
          <div class="h-[360px] flex flex-col place-items-end relative mb-4">
            <div class="p-2 rounded-xl bg-[#1280EC] text-white absolute bottom-4 left-8 transition-all">
              Hey, what is your name? 👋
              <div class="absolute bottom-[-2px] left-[-8px]">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="19"
                height="16"
                viewBox="0 0 19 16"
                fill="none"
              >
                <path
                  d="M1.90735e-06 14.7395C9.10227 16.3944 16.0324 11.6364 18.3597 9.05055L18.1011 1.29294C15.6014 1.81011 10.1883 2.27557 8.53338 0C8.79197 9.30914 1.81011 13.9637 1.90735e-06 14.7395Z"
                  fill="#1381EE"
                />
              </svg>
            </div>
            </div>
          </div>
          <div class="w-full flex gap-3 pl-3 pr-3 h-[64px] place-items-center justify-between">
            <Menu as="div" className="relative inline-block text-left">
              <div>
                <Menu.Button className="w-full h-[48px] flex place-items-center justify-center rounded-full border bg-white border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 transition-all">
                  <Icon.Smartphone />
                </Menu.Button>
              </div>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-100"
                enterFrom="transform opacity-0 scale-95"
                enterTo="transform opacity-100 scale-100"
                leave="transition ease-in duration-75"
                leaveFrom="transform opacity-100 scale-100"
                leaveTo="transform opacity-0 scale-95"
              >
                <Menu.Items className="absolute overflow-hidden left-0 top-[-150px] z-10 w-56 origin-bottom-left rounded-xl bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                  <div className="py-0">
                    <Link href="#">
                      <Menu.Item>
                        {({ active }) => (
                          <button
                            type="submit"
                            className={classNames(
                              active
                                ? "bg-gray-100 text-gray-900 border-l-[#1480EB]"
                                : "text-gray-700 border-l-transparent",
                              "block w-full px-4 py-2 text-left text-sm font-medium border-l-2"
                            )}
                          >
                            Sign out
                          </button>
                        )}
                      </Menu.Item>
                    </Link>
                    <Link href="#">
                      <Menu.Item>
                        {({ active }) => (
                          <button
                            type="submit"
                            className={classNames(
                              active
                                ? "bg-gray-100 text-gray-900 border-l-[#1480EB]"
                                : "text-gray-700 border-l-transparent",
                              "block w-full px-4 py-2 text-left text-sm font-medium border-l-2"
                            )}
                          >
                            Sign out
                          </button>
                        )}
                      </Menu.Item>
                    </Link>
                    <Link href="#">
                      <Menu.Item>
                        {({ active }) => (
                          <button
                            type="submit"
                            className={classNames(
                              active
                                ? "bg-gray-100 text-gray-900 border-l-[#1480EB]"
                                : "text-gray-700 border-l-transparent",
                              "block w-full px-4 py-2 text-left text-sm font-medium border-l-2"
                            )}
                          >
                            Sign out
                          </button>
                        )}
                      </Menu.Item>
                    </Link>
                    <Link href="#">
                      <Menu.Item>
                        {({ active }) => (
                          <button
                            type="submit"
                            className={classNames(
                              active
                                ? "bg-gray-100 text-gray-900 border-l-[#1480EB]"
                                : "text-gray-700 border-l-transparent",
                              "block w-full px-4 py-2 text-left text-sm font-medium border-l-2"
                            )}
                          >
                            Sign out
                          </button>
                        )}
                      </Menu.Item>
                    </Link>
                  </div>
                </Menu.Items>
              </Transition>
            </Menu>
            <div class="w-[90%] h-[48px] bg-white rounded-full border border-solid border-gray-300 relative text-sm">
              <input class="absolute top-0 right-0 left-0 bottom-0 rounded-full p-3" placeholder="Enter your message"></input>
              <Icon.ArrowUp class="right-2 text-white bg-[#1480EB] absolute rounded-full p-1 cursor-pointer top-[50%] translate-y-[-50%] hover:bg-[#2795FD] transition-all" size={28} />
            </div>
          </div>
        </div>
        <div class="h-64"></div>
      </main>
      <Footer />
    </>
  );
}
