import Head from "next/head";
import * as React from "react";
import { useState, useMemo, useEffect } from "react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import Contact from "@/components/Contact";
import Image from "next/image";
import Link from "next/link";
import * as Icon from "react-feather";
import { useIsVisible } from "@/hooks/useIsVisible";

export default function Home() {
  const title = "Designer and Developer";
  const imgLoader = ({ src, width, quality }) => {
    return `/${src}?w=${width}&q=${quality || 75}`;
  };
  const [item, setItem] = useState(0);
  const [highlight, setHighlight] = useState("Home");
  const rect = React.useRef(null);
  const projects = React.useRef(null);
  const isVisible = useIsVisible(projects);

  const changeItem = () => {
    if (item === 0) {
      setItem(1);
      rect.current.style.transform = "translateX(48px) translateY(-50%)";
    } else {
      setItem(0);
      rect.current.style.transform = "translateX(0%) translateY(-50%)";
    }
  };

  useEffect(() => {
    if (isVisible) {
      setHighlight("Projects");
    } else {
      setHighlight("Home");
    }
  }, [isVisible]);

  return (
    <>
      <Head>
        <title>Combining Design and Technology | Design With Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation title={title} highlight={highlight} />
      <main class="max-md:w-[90%] w-full max-w-6xl pl-[5%] pr-[5%] m-auto bg-white">
        <div class="h-[70vh] flex place-items-center justify-between">
          <div class="md:w-[50%]">
            <h1 class="text-5xl font-bold mb-6">Hey, I'm Florian</h1>
            <h2 class="text-3xl font-medium text-gray-700">
              A designer and developer building digital products.
            </h2>
            <div class="h-8"></div>
            <Link
              class="p-4 w-full max-w-[400px] flex place-items-center gap-6 bg-gray-100 border border-gray-300 transition-all hover:bg-gray-50 hover:border-gray-200 border-solid rounded-2xl"
              href={"./#contact"}
            >
              <div class="h-[8px] w-[8px] flex-none flex justify-center place-items-center rounded-full bg-red-600 opacity-75">
                <div class="animate-ping h-[16px] w-[16px] absolute flex-none rounded-full bg-red-500 opacity-75"></div>
              </div>
              <p class="font-medium text-sm">
                Currently I am looking for internship opportunities in Europe or
                North America.
              </p>
            </Link>
          </div>
          <Image
            loader={imgLoader}
            src="./images/main_header.png"
            alt="Header Image of Florian as Cartoon Character"
            class="mix-blend-exclusion max-md:hidden"
            width={250}
            height={250}
          />
        </div>
        <div>
          <h2 class="text-2xl font-medium text-black">
            As a designer and developer I see my role in leading projects that
            help companies to achieve their ambitious goals in creating
            something functionally and technologically useful for humanity
          </h2>
        </div>
        <div class="h-64"></div>
        <div>
          <div class="flex justify-between pb-[40px]">
            <h2 class="text-3xl font-medium text-black">Some of my projects</h2>
            <div class="max-md:hidden flex gap-6 relative place-items-center pl-2 pr-2">
              <Icon.Grid
                onClick={changeItem}
                class="cursor-pointer text-gray-600 hover:text-black transition-all relative z-10"
              />
              <Icon.List
                onClick={changeItem}
                class="cursor-pointer text-gray-600 hover:text-black transition-all relative z-10"
              />
              <div
                ref={rect}
                class="w-[40px] h-[40px] left-0 top-[50%] translate-y-[-50%] rounded-md absolute bg-gray-100 border border-gray-200 transition-all"
              ></div>
            </div>
          </div>
          <div ref={projects} id="projects">
            <div
              class={
                !item ? "grid gap-8 md:grid-cols-2" : "grid gap-8 grid-cols-1"
              }
            >
              <Link
                href={"./projects/boost"}
                class={!item ? "group" : "group grid grid-cols-2 gap-8 place-items-center"}
              >
                <div class="bg-white shadow-md ring-1 ring-gray-100 rounded-md p-2 mb-6 mt-6">
                  <Image
                    loader={imgLoader}
                    src="./images/boost/boost.jpg"
                    alt="Photo of the Boost Device"
                    class="w-full max-h-[272px] object-cover group-hover:opacity-80 transition-all"
                    width={350}
                    height={250}
                  />
                </div>
                <div>
                  <div class="flex place-items-center gap-2">
                    <h3 class="text-xl font-medium pb-1">Boost</h3>
                    <Icon.ArrowRight class="opacity-0 group-hover:opacity-100 transition-all relative" />
                  </div>
                  <p class="pb-2 text-gray-600">
                    Mobile application and hardware device to calculate
                    nutrition intake and provide personalized nutrition
                  </p>

                  <div class="flex gap-4 text-xs text-gray-500">
                    <div class="flex gap-2 place-items-center">
                      <Icon.Calendar width={16} />
                      <p>Q1 2023</p>
                    </div>
                    <div class="flex gap-2 place-items-center">
                      <Icon.MapPin width={16} />
                      <p>Schwaebisch Gmuend</p>
                    </div>
                  </div>
                </div>
              </Link>

              <Link
                href={"/projects/curations"}
                class={!item ? "group" : "group grid grid-cols-2 gap-8 place-items-center"}
              >
                <div class="bg-white shadow-md ring-1 ring-gray-100 rounded-md p-2 mb-6 mt-6">
                  <Image
                    loader={imgLoader}
                    src="./images/curations/curations.jpg"
                    alt="Image of Curations in a Mockup"
                    class="w-full max-h-[272px] object-cover group-hover:opacity-80 transition-all"
                    width={350}
                    height={250}
                  />
                </div>
                <div>
                  <div class="flex place-items-center gap-2">
                    <h3 class="text-xl font-medium pb-1">Curations</h3>
                    <Icon.ArrowRight class="opacity-0 group-hover:opacity-100 transition-all relative" />
                  </div>
                  <p class="pb-2 text-gray-600">
                    Website featuring useful curations for designers and
                    developers
                  </p>
                  <div class="flex gap-4 text-xs text-gray-500">
                    <div class="flex gap-2 place-items-center">
                      <Icon.Calendar width={16} />
                      <p>Q4 2022</p>
                    </div>
                    <div class="flex gap-2 place-items-center">
                      <Icon.MapPin width={16} />
                      <p>Schwaebisch Gmuend</p>
                    </div>
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>
        <div class="h-64"></div>
        <div class="flex gap-8 justify-between max-md:flex-col ">
          <div class="md:max-w-[50%]">
            <h2 class="text-2xl font-medium mb-4">More to my person</h2>
            <p class="text-gray-600">
              Being interested in technology and design would be a big
              understatement. I love creating useful products, trying out new
              things and adjusting key levers as long as necessary to give
              people the best experience possible. <br />
              <br /> The reason for doing this, is because I see myself not only
              as a designer or engineer of a product, much more can I imagine
              myself as the end-user that wants to have an accessible product
              that's usable. <br />
              <br /> If you want to read more to myself, you can click the
              button below or find me on{" "}
              <Link
                href="https://read.cv/floriandwt"
                target={"_blank"}
                class="text-[#1281ed] inline-block border border-solid border-blue-100 rounded-md pl-1 pr-1"
              >
                Read.cv
              </Link>
              .
            </p>
            <div class="h-8"></div>
            <Link
              class="bg-white text-black pr-4 pl-4 pt-2 pb-2 rounded-md hover:bg-gray-100 transition-all font-medium border border-solid border-gray-300"
              href="./about"
            >
              About me
            </Link>
          </div>
          <Image
            loader={imgLoader}
            src="./images/florian_student.jpg"
            alt="Image of Florian as a student"
            class="w-full h-full max-md:order-first max-md:mb-8 max-w-[350px] max-h-[500px] object-cover group-hover:opacity-80 transition-all rotate-3"
            width={250}
            height={600}
          />
        </div>
        <div class="h-64"></div>
        <Contact />
        <div class="h-64"></div>
      </main>
      <Footer />
    </>
  );
}
