/**
 * Scans public/images for raster images and emits a manifest with intrinsic
 * dimensions + a tiny base64 blur placeholder, so the shared <Image> component
 * can reserve space (no layout shift) and render a Next-style blur-up.
 *
 * Output: src/generated/image-manifest.ts
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname!, "..");
const PUBLIC_DIR = path.join(ROOT, "public");
const IMAGES_DIR = path.join(PUBLIC_DIR, "images");
const OUTPUT_PATH = path.join(ROOT, "src/imageMap.gen.ts");

const RASTER = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);
const SVG = ".svg";

interface Entry {
  width: number;
  height: number;
  blurDataURL: string | null;
}

function parseSvgDimensions(source: string): { width: number; height: number } | null {
  const tagMatch = source.match(/<svg\b[^>]*>/i);
  if (!tagMatch) return null;
  const tag = tagMatch[0];

  const attrNum = (name: string): number | null => {
    const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]+)"`, "i"));
    if (!m) return null;
    const n = parseFloat(m[1]);
    return Number.isFinite(n) ? n : null;
  };

  const w = attrNum("width");
  const h = attrNum("height");
  if (w && h) return { width: w, height: h };

  const viewBox = tag.match(/\bviewBox\s*=\s*"([^"]+)"/i);
  if (viewBox) {
    const parts = viewBox[1]
      .trim()
      .split(/[\s,]+/)
      .map(parseFloat);
    if (parts.length === 4 && parts.every((n) => Number.isFinite(n))) {
      return { width: parts[2], height: parts[3] };
    }
  }
  return null;
}

function walk(dir: string, out: string[] = []): string[] {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

async function processImage(absPath: string): Promise<[string, Entry] | null> {
  const ext = path.extname(absPath).toLowerCase();
  const publicPath = "/" + path.relative(PUBLIC_DIR, absPath).split(path.sep).join("/");

  if (ext === SVG) {
    const dims = parseSvgDimensions(fs.readFileSync(absPath, "utf-8"));
    if (!dims) return null;
    return [publicPath, { width: dims.width, height: dims.height, blurDataURL: null }];
  }

  if (!RASTER.has(ext)) return null;

  const image = sharp(absPath);
  const meta = await image.metadata();
  if (!meta.width || !meta.height) return null;

  const blurBuffer = await image
    .clone()
    .resize(40, undefined, { fit: "inside" })
    .jpeg({ quality: 45 })
    .toBuffer();
  const blurDataURL = `data:image/jpeg;base64,${blurBuffer.toString("base64")}`;

  return [publicPath, { width: meta.width, height: meta.height, blurDataURL }];
}

async function main() {
  if (!fs.existsSync(IMAGES_DIR)) {
    console.warn(`[image-manifest] ${IMAGES_DIR} does not exist, skipping`);
    return;
  }

  const files = walk(IMAGES_DIR);
  const entries = await Promise.all(files.map(processImage));
  const manifest: Record<string, Entry> = {};
  for (const e of entries) {
    if (e) manifest[e[0]] = e[1];
  }

  const sorted = Object.keys(manifest).sort();
  const body = sorted
    .map((k) => {
      const { width, height, blurDataURL } = manifest[k];
      const blur = blurDataURL === null ? "null" : JSON.stringify(blurDataURL);
      return `  ${JSON.stringify(k)}: { width: ${width}, height: ${height}, blurDataURL: ${blur} },`;
    })
    .join("\n");

  const source = `// Generated by scripts/build-image-manifest.ts — do not edit by hand.
export interface ImageManifestEntry {
  width: number;
  height: number;
  blurDataURL: string | null;
}

export const imageManifest: Record<string, ImageManifestEntry> = {
${body}
};
`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, source);
  console.log(
    `[image-manifest] wrote ${sorted.length} entries to ${path.relative(ROOT, OUTPUT_PATH)}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
