// Emits src/videoMap.gen.ts with video dimensions + a first-frame ThumbHash so <Video> reserves space and shows a blur-up.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import sharp from "sharp";
import { rgbaToThumbHash } from "thumbhash";

const ROOT = path.resolve(import.meta.dirname!, "..");
const PUBLIC_DIR = path.join(ROOT, "public");
const VIDEOS_DIR = path.join(PUBLIC_DIR, "videos");
const OUTPUT_PATH = path.join(ROOT, "src/videoMap.gen.ts");

const VIDEO_EXT = new Set([".webm", ".mp4", ".mov", ".m4v"]);

interface Entry {
  width: number;
  height: number;
  thumbhash: string | null;
}

function walk(dir: string, out: string[] = []): string[] {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function probeDimensions(absPath: string): { width: number; height: number } | null {
  try {
    const json = execFileSync(
      "ffprobe",
      [
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height",
        "-of",
        "json",
        absPath,
      ],
      { encoding: "utf-8" },
    );
    const data = JSON.parse(json);
    const stream = data.streams?.[0];
    if (!stream?.width || !stream?.height) return null;
    return { width: stream.width, height: stream.height };
  } catch {
    return null;
  }
}

async function extractThumbhash(absPath: string): Promise<string | null> {
  const tmp = path.join(os.tmpdir(), `mediamanifest-${process.pid}-${Date.now()}.png`);
  try {
    execFileSync(
      "ffmpeg",
      ["-y", "-v", "error", "-i", absPath, "-vf", "select=eq(n\\,0)", "-vframes", "1", tmp],
      { stdio: ["ignore", "ignore", "ignore"] },
    );
    if (!fs.existsSync(tmp)) return null;
    const { data, info } = await sharp(tmp)
      .resize(100, 100, { fit: "inside" })
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    const hash = rgbaToThumbHash(info.width, info.height, data);
    return Buffer.from(hash).toString("base64");
  } catch {
    return null;
  } finally {
    if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
  }
}

async function processVideo(absPath: string): Promise<[string, Entry] | null> {
  const ext = path.extname(absPath).toLowerCase();
  if (!VIDEO_EXT.has(ext)) return null;

  const dims = probeDimensions(absPath);
  if (!dims) return null;
  const thumbhash = await extractThumbhash(absPath);

  const publicPath = "/" + path.relative(PUBLIC_DIR, absPath).split(path.sep).join("/");
  return [publicPath, { width: dims.width, height: dims.height, thumbhash }];
}

async function main() {
  if (!fs.existsSync(VIDEOS_DIR)) {
    console.warn(`[video-manifest] ${VIDEOS_DIR} does not exist, skipping`);
    return;
  }

  const files = walk(VIDEOS_DIR);
  const entries = await Promise.all(files.map(processVideo));
  const manifest: Record<string, Entry> = {};
  for (const e of entries) {
    if (e) manifest[e[0]] = e[1];
  }

  const sorted = Object.keys(manifest).sort();
  const body = sorted
    .map((k) => {
      const { width, height, thumbhash } = manifest[k];
      const hash = thumbhash === null ? "null" : JSON.stringify(thumbhash);
      return `  ${JSON.stringify(k)}: { width: ${width}, height: ${height}, thumbhash: ${hash} },`;
    })
    .join("\n");

  const source = `// Generated by scripts/build-video-manifest.ts — do not edit by hand.
export interface VideoManifestEntry {
  width: number;
  height: number;
  thumbhash: string | null;
}

export const videoManifest: Record<string, VideoManifestEntry> = {
${body}
};
`;

  fs.writeFileSync(OUTPUT_PATH, source);
  console.log(
    `[video-manifest] wrote ${sorted.length} entries to ${path.relative(ROOT, OUTPUT_PATH)}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
