/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as ColophonRouteImport } from './routes/colophon'
import { Route as ClaudeInstallationRouteImport } from './routes/claude-installation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingIdRouteImport } from './routes/writing/$id'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ColophonRoute = ColophonRouteImport.update({
  id: '/colophon',
  path: '/colophon',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeInstallationRoute = ClaudeInstallationRouteImport.update({
  id: '/claude-installation',
  path: '/claude-installation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIdRoute = WritingIdRouteImport.update({
  id: '/writing/$id',
  path: '/writing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claude-installation': typeof ClaudeInstallationRoute
  '/colophon': typeof ColophonRoute
  '/experiments': typeof ExperimentsRoute
  '/imprint': typeof ImprintRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/writing/$id': typeof WritingIdRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claude-installation': typeof ClaudeInstallationRoute
  '/colophon': typeof ColophonRoute
  '/experiments': typeof ExperimentsRoute
  '/imprint': typeof ImprintRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/writing/$id': typeof WritingIdRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claude-installation': typeof ClaudeInstallationRoute
  '/colophon': typeof ColophonRoute
  '/experiments': typeof ExperimentsRoute
  '/imprint': typeof ImprintRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/writing/$id': typeof WritingIdRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/claude-installation'
    | '/colophon'
    | '/experiments'
    | '/imprint'
    | '/privacy-policy'
    | '/writing/$id'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/claude-installation'
    | '/colophon'
    | '/experiments'
    | '/imprint'
    | '/privacy-policy'
    | '/writing/$id'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/claude-installation'
    | '/colophon'
    | '/experiments'
    | '/imprint'
    | '/privacy-policy'
    | '/writing/$id'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClaudeInstallationRoute: typeof ClaudeInstallationRoute
  ColophonRoute: typeof ColophonRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  WritingIdRoute: typeof WritingIdRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colophon': {
      id: '/colophon'
      path: '/colophon'
      fullPath: '/colophon'
      preLoaderRoute: typeof ColophonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-installation': {
      id: '/claude-installation'
      path: '/claude-installation'
      fullPath: '/claude-installation'
      preLoaderRoute: typeof ClaudeInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$id': {
      id: '/writing/$id'
      path: '/writing/$id'
      fullPath: '/writing/$id'
      preLoaderRoute: typeof WritingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClaudeInstallationRoute: ClaudeInstallationRoute,
  ColophonRoute: ColophonRoute,
  ExperimentsRoute: ExperimentsRoute,
  ImprintRoute: ImprintRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  WritingIdRoute: WritingIdRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
