// Generated by scripts/build-video-manifest.ts — do not edit by hand.
export interface VideoManifestEntry {
  width: number;
  height: number;
  thumbhash: string | null;
}

export const videoManifest: Record<string, VideoManifestEntry> = {};
