name: Links

on:
  push:
    branches:
      - "main"
      - "redesign-2"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: false
          args: --verbose --no-progress './pages/*/*.tsx' './**/*.md'
